# """
# Django settings for rag_portfolio project.

# Generated by 'django-admin startproject' using Django 5.2.15.

# For more information on this file, see
# https://docs.djangoproject.com/en/5.2/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/5.2/ref/settings/
# """

# from pathlib import Path

# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent


# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-mhz%vvebef4r0kx!jom0ghbpm^sf@ii#o@-=j_!rjj7%e^@ms9'

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = [
#     "localhost",
#     "127.0.0.1",
#     "your-backend-name.up.railway.app",
# ]

# # Application definition

# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'assitant',
#     'corsheaders',
# ]

# MIDDLEWARE = [
#     'corsheaders.middleware.CorsMiddleware',
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]

# ROOT_URLCONF = 'rag_portfolio.urls'
# import os
# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [os.path.join(BASE_DIR, 'static/templates')],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = 'rag_portfolio.wsgi.application'


# # Database
# # https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = { 
#    "default": { 
#        "ENGINE": "django.db.backends.postgresql", 
#        "NAME": "rag_portfolio", 
#        "USER": "postgres", 
#        "PASSWORD": "7010", 
#        "HOST": "127.0.0.1", 
#        "PORT": "5432", 
#    } 
# }


# # Password validation
# # https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# # Internationalization
# # https://docs.djangoproject.com/en/5.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

# USE_I18N = True

# USE_TZ = True


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = 'static/'

# # Default primary key field type
# # https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# STATIC_URL = 'static/'


# STATIC_ROOT = BASE_DIR / "staticfiles"

# from dotenv import load_dotenv

# load_dotenv()

# os.getenv("GROQ_API_KEY")



# from datetime import timedelta

# SESSION_COOKIE_AGE = 1800          # 30 minutes
# SESSION_SAVE_EVERY_REQUEST = False
# SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:5500",
#     "http://127.0.0.1:5500",
#     "https://askrithik.netlify.app",
# ]

# CSRF_TRUSTED_ORIGINS = [
#     "http://localhost:5500",
#     "http://127.0.0.1:5500",
#     "https://askrithik.netlify.app",
# ]

# CORS_ALLOW_CREDENTIALS = True 

# SESSION_COOKIE_SAMESITE = "Lax"
# SESSION_COOKIE_SECURE = False   # only for local dev over http — see note below
# CSRF_COOKIE_SAMESITE = "Lax"
# CSRF_COOKIE_SECURE = False
# # Email configuration

# import os

"""
Django settings for rag_portfolio project.

Generated by 'django-admin startproject' using Django 5.2.15.
Adapted for production deployment on Render.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""


# below is an production side 
import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv()  # loads .env locally; on Railway, env vars are injected directly


# -----------------------------------------------------------------------
# CORE SECURITY SETTINGS
# -----------------------------------------------------------------------

# SECURITY WARNING: keep the secret key used in production secret!
# Set this in your environment (.env locally, Railway "Variables" tab in prod).
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-mhz%vvebef4r0kx!jom0ghbpm^sf@ii#o@-=j_!rjj7%e^@ms9",  # dev-only fallback
)

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False; set DJANGO_DEBUG=True in your local .env for development.
DEBUG = os.getenv("DJANGO_DEBUG", "False") == "True"

ALLOWED_HOSTS = [
    h.strip()
    for h in os.getenv(
        "DJANGO_ALLOWED_HOSTS",
        "localhost,127.0.0.1,your-backend-name.onrender.com",
    ).split(",")
    if h.strip()
]

# Render automatically injects RENDER_EXTERNAL_HOSTNAME with your service's
# actual *.onrender.com domain — add it automatically so you don't have to
# hardcode/update it manually after every deploy.
RENDER_EXTERNAL_HOSTNAME = os.getenv("RENDER_EXTERNAL_HOSTNAME")
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


# -----------------------------------------------------------------------
# APPLICATION DEFINITION
# -----------------------------------------------------------------------

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'assitant',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # serves static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'rag_portfolio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'static/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rag_portfolio.wsgi.application'


# -----------------------------------------------------------------------
# DATABASE
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# -----------------------------------------------------------------------

# Prefer a single DATABASE_URL (Render provides this automatically when you
# create a PostgreSQL instance and link it to your web service). Falls back
# to individual env vars for local dev.
DATABASE_URL = os.getenv("DATABASE_URL")

if DATABASE_URL:
    import dj_database_url

    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=os.getenv("DJANGO_DB_SSL_REQUIRE", "True") == "True",
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("DB_NAME", "rag_portfolio"),
            "USER": os.getenv("DB_USER", "postgres"),
            "PASSWORD": os.getenv("DB_PASSWORD", ""),
            "HOST": os.getenv("DB_HOST", "127.0.0.1"),
            "PORT": os.getenv("DB_PORT", "5432"),
        }
    }


# -----------------------------------------------------------------------
# PASSWORD VALIDATION
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
# -----------------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# -----------------------------------------------------------------------
# INTERNATIONALIZATION
# https://docs.djangoproject.com/en/5.2/topics/i18n/
# -----------------------------------------------------------------------

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# -----------------------------------------------------------------------
# STATIC FILES (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
# -----------------------------------------------------------------------

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise: compressed, cache-busted static file storage for production.
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# -----------------------------------------------------------------------
# THIRD-PARTY API KEYS
# -----------------------------------------------------------------------

GROQ_API_KEY = os.getenv("GROQ_API_KEY")


# -----------------------------------------------------------------------
# SESSIONS
# -----------------------------------------------------------------------

SESSION_COOKIE_AGE = 1800          # 30 minutes
SESSION_SAVE_EVERY_REQUEST = False
SESSION_EXPIRE_AT_BROWSER_CLOSE = False


# -----------------------------------------------------------------------
# CORS / CSRF
# -----------------------------------------------------------------------

CORS_ALLOWED_ORIGINS = [
    o.strip()
    for o in os.getenv(
        "CORS_ALLOWED_ORIGINS",
        "http://localhost:5500,http://127.0.0.1:5500,https://askrithik.netlify.app",
    ).split(",")
    if o.strip()
]

CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.getenv(
        "CSRF_TRUSTED_ORIGINS",
        "http://localhost:5500,http://127.0.0.1:5500,https://askrithik.netlify.app,https://your-backend-name.onrender.com",
    ).split(",")
    if o.strip()
]

# Auto-add Render's dynamically-assigned hostname to CSRF trusted origins.
if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(f"https://{RENDER_EXTERNAL_HOSTNAME}")

CORS_ALLOW_CREDENTIALS = True

# In production, cookies must be Secure + SameSite=None (or Lax if
# frontend/backend share a top-level site) since traffic is HTTPS.
SESSION_COOKIE_SAMESITE = "None" if not DEBUG else "Lax"
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SAMESITE = "None" if not DEBUG else "Lax"
CSRF_COOKIE_SECURE = not DEBUG


# -----------------------------------------------------------------------
# PRODUCTION-ONLY SECURITY HARDENING
# https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
# -----------------------------------------------------------------------

if not DEBUG:
    # Render (and most PaaS) terminate TLS at a proxy and forward requests
    # over HTTP internally, adding this header so Django knows it was HTTPS.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = os.getenv("DJANGO_SECURE_SSL_REDIRECT", "True") == "True"

    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 7  # 1 week; raise once confident (e.g. 31536000)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = "DENY"


# -----------------------------------------------------------------------
# LOGGING (basic production-friendly console logging)
# -----------------------------------------------------------------------

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "root": {
        "handlers": ["console"],
        "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
    },
}