# Generated by Django 5.2.15 on 2026-07-01 05:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assitant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmstatus',
            name='requests_used_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='llmstatus',
            name='tokens_used_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='llmstatus',
            name='usage_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
