# Generated by Django 5.2.15 on 2026-07-01 06:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assitant', '0002_llmstatus_requests_used_today_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('audio_seconds', models.FloatField(default=0)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RemoveField(
            model_name='llmstatus',
            name='requests_used_today',
        ),
        migrations.RemoveField(
            model_name='llmstatus',
            name='tokens_used_today',
        ),
        migrations.RemoveField(
            model_name='llmstatus',
            name='usage_date',
        ),
    ]
